# right arm compliant controller ---------------------------------------
  right_arm_compliant_controller:
    type: "position_controllers/CompliantController"
    ft_sensor_name: right_hand_ft_sensor
    joints:
      - r_arm_shy
      - r_arm_shx
      - r_arm_ely
      - r_arm_elx
      - r_arm_wry
      - r_arm_wrx
    segments:
      - utorso
      - r_clav
      - r_scap
      - r_uarm
      - r_larm
      - r_farm
      - r_hand
    moveit_group: "r_arm_group"
    inertia: "150,150,150,150,150,150"
    damping: "250,250,250,250,250,250"
    stiffness: "400,400,400,400,400,400"
    cmd_topic_name: "/r_arm_pose"
