# trajectory controllers ---------------------------------------
  right_arm_compliant_controller:
    type: "velocity_controllers/CompliantController"
    ft_sensor_name: right_hand_ft_sensor
    joints:
      - r_arm_shy
      - r_arm_shx
      - r_arm_ely
      - r_arm_elx
      - r_arm_wry
      - r_arm_wrx
    segments:
      - utorso
      - r_clav
      - r_scap
      - r_uarm
      - r_larm
      - r_farm
      - r_hand
#    constraints:
#      goal_time: &goal_time_constraint 0.6
#      l_arm_shy:
#        goal: &goal_pos_constraint 0.02
#      l_arm_shx:
#        goal: *goal_pos_constraint
#      l_arm_ely:
#        goal: *goal_pos_constraint
#      l_arm_elx:
#        goal: *goal_pos_constraint
#      l_arm_wry:
#        goal: *goal_pos_constraint
#      l_arm_wrx:
#        goal: *goal_pos_constraint
        
#    stop_trajectory_duration: 0.0
#    state_publish_rate: 1000.0
